# Generated by Django 4.2.6 on 2023-10-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descounted_price',
            new_name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
    ]
