# Generated by Django 4.2.6 on 2023-10-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_place', '0002_rename_descounted_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Moscow', 'Moscow'), ('Saint Petersburg', 'Saint Petersburg'), ('Novosibirsk', 'Novosibirsk'), ('Yekaterinburg', 'Yekaterinburg'), ('Nizhny Novgorod', 'Nizhny Novgorod'), ('Kazan', 'Kazan'), ('Chelyabinsk', 'Chelyabinsk'), ('Omsk', 'Omsk'), ('Samara', 'Samara'), ('Rostov-on-Don', 'Rostov-on-Don'), ('Ufa', 'Ufa'), ('Krasnoyarsk', 'Krasnoyarsk'), ('Perm', 'Perm'), ('Volgograd', 'Volgograd'), ('Voronezh', 'Voronezh'), ('Krasnodar', 'Krasnodar'), ('Saratov', 'Saratov'), ('Tyumen', 'Tyumen'), ('Tolyatti', 'Tolyatti'), ('Izhevsk', 'Izhevsk'), ('Ulyanovsk', 'Ulyanovsk')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
