# Generated by Django 4.2.6 on 2023-10-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0006_alter_orderplaced_status_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Saint Petersburg', 'Saint Petersburg'), ('Novosibirsk', 'Novosibirsk'), ('Yekaterinburg', 'Yekaterinburg'), ('Nizhny Novgorod', 'Nizhny Novgorod'), ('Kazan', 'Kazan'), ('Chelyabinsk', 'Chelyabinsk'), ('Omsk', 'Omsk'), ('Samara', 'Samara'), ('Rostov-on-Don', 'Rostov-on-Don'), ('Ufa', 'Ufa'), ('Krasnoyarsk', 'Krasnoyarsk'), ('Perm', 'Perm'), ('Volgograd', 'Volgograd'), ('Voronezh', 'Voronezh'), ('Krasnodar', 'Krasnodar'), ('Saratov', 'Saratov'), ('Tyumen', 'Tyumen'), ('Tolyatti', 'Tolyatti'), ('Izhevsk', 'Izhevsk'), ('Ulyanovsk', 'Ulyanovsk')], max_length=100),
        ),
    ]
